import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotificationProvider } from "./context/NotificationContext";
import { BackHomeButton } from "@/components/BackHomeButton";
import { NotificationBanner } from "@/components/NotificationBanner";
import { ThemeProvider } from "./context/ThemeContext";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { ThemeSwitch } from "@/components/ThemeSwitch";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//bg-gradient-to-b  from-gray-50 to-gray-100
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  dark:from-gray-900 dark:to-gray-800`}
      >
        {/* <NextThemesProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          > */}
        <ThemeProvider>
          <NotificationProvider>
            <div className="flex justify-between">
              <BackHomeButton></BackHomeButton>
              <ThemeSwitch />
            </div>

            <NotificationBanner />

            {children}
          </NotificationProvider>
        </ThemeProvider>
        {/* </NextThemesProvider> */}
      </body>
    </html>
  );
}
